名称：VC6到VS2022

：请将以下网页文本翻译成中文，只输出翻译结果，不输出任何其他解释，若文本已经是中文了，则直接用中文复述一遍。翻译结果保持格式不变。输入：:
  推:
    分支：
      -主页
  拉取请求:
    分支：
      -主页

工作：
  转换：
    运行于：Windows-latest

    步骤：
      - 名称：结账代码
        使用：actions/checkout@v3

      - 名称：设置 Visual Studio 开发环境
        运行： |
          调用 "call "D:\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat""D:\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat""
          echo 当前目录：$(cd)

      - 名称：      - 名称： 将VC6项目升级到VS2022
        运行： |
          cd /d "D:\gh\VC6.0toVS2022-main\VC6.0马里奥\新建文件夹"&D:\gh\VC6.0toVS2022-main\VC6.0马里奥\新建文件夹&D
          echo 正在升级 mario01.dsp...
          devenv.com /upgrade “mario01.dsp”“mario01.dsp”
          echo 正在升级 mario01.dsw...
          devenv.com /upgrade “mario01.dsw”

      - 名称：      - 名称： 建设项目
        运行： |
          cd /d "D:\gh\VC6.0toVS2022-main\VC6.0马里奥\新建文件夹"&D:\gh\VC6.0toVS2022-main\VC6.0马里奥\新建文件夹&D
          msbuild /p:Configuration=Release /p:Platform=x64 "mario01.vcxproj"&mario01.vcxproj"

      -      - 名称：上传构建产物
        使用：actions/upload-artifact@v3
        与：
          名称：构建工件
          路径： |
            D:\gh\VC6.0toVS2022-main\VC6.0马里奥\新建文件夹\Release\
            D:\gh\VC6.0toVS2022-main\VC6.0马里奥\新建文件夹\Debug\
