name: VC6toVS2022

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Upgrade VC6 Projects
        run: |
          echo "Upgrading VC6 projects to VS2022..."
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          cd "VC6.0马里奥/新建文件夹"
          devenv.com /upgrade "mario01.dsp"
          devenv.com /upgrade "mario01.dsw"

      - name: Build upgraded projects
        run: |
          msbuild /p:Configuration=Release /p:Platform=x64 "VC6.0马里奥/新建文件夹/mario01.vcxproj"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BuildArtifacts
          path: |
            VC6.0马里奥/新建文件夹/Debug/
            VC6.0马里奥/新建文件夹/Release/
